version: '3.8'

services:
  app:
    build: .
    ports:
      - "7777:7777"
    environment:
      - JDBC_URL=jdbc:mysql://mysql:3306/your_database
      - DRIVER=com.mysql.cj.jdbc.Driver
      - USER=your_username
      - PASSWORD=your_password
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
